name: Feature Request
description: Suggest a new feature for HeroUI MCP Server
title: "[FEATURE] "
labels: ["enhancement", "triage"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: Brief description of the feature
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
    validations:
      required: true
